Update Pipline Script

diff --git a/Pipline Script b/Pipline Script
--- a/Pipline Script
+++ b/Pipline Script
@@ -1,13 +1,8 @@
 node('jenkins_bu') {
-  stage('Change Directory To Jenkins Home') {
-    HOME = "/root/.jenkins"
-    sh "cd ${HOME}"
-  }
   stage('Create Jenkins Arcive') {
-    sh '/root/.jenkins/workspace/Jenkins-Master-BU/create_tar_archive.sh'
-  }
-  stage('Add BUILD_NUMBER Suffix') {
-    sh 'mv jenkins_6.tgz jenkins_6_${BUILD_NUMBER}.tgz'
+    sh '''#!/bin/bash -xe
+             tar cpzf jenkins_6_${BUILD_NUMBER}.tgz /root/.jenkins --warning=no-file-changed --exclude="./workspace" || ( export ret=$?; [[ $ret -eq 1 ]] || exit "$ret" )
+       '''
   }
   stage('Upload Backup Arcive To Network Share') {
     sh 'pv jenkins_6_${BUILD_NUMBER}.tgz > /media/common/IT/jenkins_8/Server_6/jenkins_6_${BUILD_NUMBER}.tgz'
@@ -16,12 +11,19 @@ node('jenkins_bu') {
     sh 'sshpass -f PW.txt ssh -tt -o StrictHostKeyChecking=no admin@yifileserver "find /share/Common/IT/jenkins_8/Server_6 -mtime +7 -type f | xargs rm -f"'
   }
   stage('Archive Inegrity Check') {
-    catchError {sh '/root/.jenkins/workspace/Jenkins-Master-BU/md5-check.sh'}
-    step([$class: 'Mailer', notifyEveryUnstableBuild: true, recipients: 'user_to@mycompany.com', sendToIndividuals: true])
+    catchError {sh '''#!/bin/bash -xe
+                   md5sum /media/common/IT/jenkins_8/Server_6/jenkins_6_${BUILD_NUMBER}.tgz > jenkins_6_${BUILD_NUMBER}.tgz.md5
+                   md5sum -c jenkins_6_${BUILD_NUMBER}.tgz.md5 
+                       if [ "$?" != "0" ]; then
+                          echo "SHA1 changed! Security breach? Job Will Be Marked As Failed!!!"
+                          exit -1
+                       fi
+        ''' }
+    step([$class: 'Mailer', notifyEveryUnstableBuild: true, recipients: 'igor.rabkin@xiaoyi.com', sendToIndividuals: true])
   }
   stage('Remove Original Archive File From Jenkins $HOME') {
      try {
-      sh 'rm -f /root/.jenkins/workspace/Jenkins-Master-BU/jenkins_6_*'
+      sh 'rm -f $WORKSPACE/jenkins_6_*'
         currentBuild.result = 'SUCCESS'
     } catch (any) {
         currentBuild.result = 'FAILURE'
